name: Content Edit Request
description: Request edits to website content, including text changes, image updates, or page modifications
title: "[Content Edit]: "
labels: ["content"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the MIND Platform website! Please fill out the information below to help us understand what content needs to be edited.
  
  - type: dropdown
    id: page
    attributes:
      label: Which page needs to be edited?
      description: Select the page where you want to make content changes
      options:
        - Home (index.html)
        - People (people page or individual profiles)
        - News (news posts)
        - Software (software table)
        - Publications (publications page)
        - Seminars (seminars.html)
        - Platform (platform.html)
        - Contact (contact.html)
        - Other (please specify below)
      multiple: false
    validations:
      required: true
  
  - type: input
    id: specific-location
    attributes:
      label: Specific Page/Section Location
      description: Please be as specific as possible (e.g., "John Doe's profile under People", "News post from Jan 2024", "Research section on home page")
      placeholder: "Example: Sarah Smith's bio in the People section"
    validations:
      required: true
  
  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current content say? (Copy and paste if possible)
      placeholder: "The current text reads..."
    validations:
      required: false
  
  - type: textarea
    id: requested-changes
    attributes:
      label: Requested Changes
      description: What changes would you like to see? Please be specific and detailed.
      placeholder: "Please update the text to say... / Please add... / Please remove..."
    validations:
      required: true
  
  - type: textarea
    id: images
    attributes:
      label: Images
      description: |
        If your content edit involves images, please:
        1. Drag and drop images directly into this text area, OR
        2. Provide links to the images, OR
        3. Describe the images that need to be added/changed
        
        **Note:** Images should be in JPG, PNG, or GIF format. For profile pictures, square images work best.
      placeholder: "Drag and drop images here or paste image URLs"
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help us make the requested changes (links to references, examples from other sites, etc.)
      placeholder: "Additional details..."
    validations:
      required: false
  
  - type: checkboxes
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this content edit?
      options:
        - label: This is time-sensitive (event announcement, critical correction, etc.)
          required: false
